"""
Fill Events

Execution confirmations from broker or paper trading simulator.
"""

from datetime import datetime
from typing import Dict, Any, Optional
from .event import Event, EventType
from .order_event import OrderSide


class FillEvent(Event):
    """
    Order fill confirmation.
    
    Generated by:
    - Paper trading simulator (immediate simulated fill)
    - FIX ExecutionReport (tag 35=8) from real broker
    
    Updates portfolio positions and cash balances.
    """
    
    def __init__(self, order_id: str, symbol: str, side: OrderSide,
                 quantity: float, fill_price: float,
                 commission: float, slippage: float = 0.0,
                 timestamp: datetime = None,
                 exchange_order_id: Optional[str] = None):
        """
        Initialize fill event.
        
        Args:
            order_id: Original order ID
            symbol: Currency pair
            side: Buy or sell
            quantity: Filled quantity
            fill_price: Execution price
            commission: Commission charged
            slippage: Slippage cost (pips)
            timestamp: Fill timestamp
            exchange_order_id: Broker's order ID (from FIX ExecutionReport)
        """
        super().__init__(EventType.FILL, timestamp)
        self.order_id = order_id
        self.symbol = symbol
        self.side = side
        self.quantity = abs(quantity)
        self.fill_price = fill_price
        self.commission = commission
        self.slippage = slippage
        self.exchange_order_id = exchange_order_id
        
        # Calculate total cost
        self.total_cost = self._calculate_total_cost()
    
    def _calculate_total_cost(self) -> float:
        """
        Calculate total cost including commission and slippage.
        
        Returns:
            Total cost (positive for buy, negative for sell)
        """
        base_cost = self.quantity * self.fill_price
        
        # Add commission and slippage
        total = base_cost + self.commission + abs(self.slippage)
        
        # Negative for sell (we receive cash)
        if self.side == OrderSide.SELL:
            total = -total
        
        return total
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for logging."""
        d = super().to_dict()
        d.update({
            'order_id': self.order_id,
            'exchange_order_id': self.exchange_order_id,
            'symbol': self.symbol,
            'side': self.side.value,
            'quantity': self.quantity,
            'fill_price': self.fill_price,
            'commission': self.commission,
            'slippage': self.slippage,
            'total_cost': self.total_cost,
        })
        return d
    
    def __repr__(self) -> str:
        return (f"FillEvent(order_id={self.order_id[:12]}, {self.side.value} "
                f"{self.quantity} {self.symbol} @ {self.fill_price:.5f})")
