"""
Signal Events

Trading signals generated by strategies.
"""

from datetime import datetime
from typing import Dict, Any, Optional
from .event import Event, EventType


class SignalEvent(Event):
    """
    Trading signal from a strategy.
    
    Indicates a desire to take a position but does not directly
    execute an order (portfolio/risk management layer decides).
    """
    
    def __init__(self, symbol: str, signal_strength: float,
                 strategy_name: str, timestamp: datetime = None,
                 metadata: Optional[Dict[str, Any]] = None):
        """
        Initialize signal event.
        
        Args:
            symbol: Currency pair
            signal_strength: Signal strength (-1.0 to 1.0)
                -1.0 = strong short
                 0.0 = neutral
                +1.0 = strong long
            strategy_name: Name of strategy generating signal
            timestamp: Signal generation timestamp
            metadata: Optional dict with signal details (e.g., indicator values)
        """
        super().__init__(EventType.SIGNAL, timestamp)
        self.symbol = symbol
        self.signal_strength = signal_strength
        self.strategy_name = strategy_name
        self.metadata = metadata or {}
        
        # Validate signal strength
        if not -1.0 <= signal_strength <= 1.0:
            raise ValueError(f"Signal strength must be [-1.0, 1.0], got {signal_strength}")
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for logging."""
        d = super().to_dict()
        d.update({
            'symbol': self.symbol,
            'signal_strength': self.signal_strength,
            'strategy_name': self.strategy_name,
            'metadata': self.metadata,
        })
        return d
    
    def __repr__(self) -> str:
        return (f"SignalEvent(symbol={self.symbol}, strength={self.signal_strength:.3f}, "
                f"strategy={self.strategy_name})")
