"""
Comprehensive Final Report Generator
Produces detailed analysis of strategy validation results
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

import pickle
import numpy as np
from datetime import datetime


def generate_final_report(
    backtest_results_file: str = 'reports/backtests/exhaustion_h1_backtest_results.pkl',
    output_file: str = 'reports/EXHAUSTION_H1_FINAL_REPORT.md'
):
    """
    Generate comprehensive final report for the exhaustion strategy.
    
    Args:
        backtest_results_file: Path to pickled backtest results
        output_file: Output markdown file path
    """
    
    # Load results
    print("Loading backtest results...")
    with open(backtest_results_file, 'rb') as f:
        results = pickle.load(f)
    
    # Load trade analysis
    from examples.analyze_trades import analyze_trades
    trade_stats, trades_df = analyze_trades(backtest_results_file)
    
    # Generate report
    print(f"Generating report to {output_file}...")
    
    report_lines = []
    
    # ========================================================================
    # Header
    # ========================================================================
    report_lines.append("# GBP/USD H1 Exhaustion Mean Reversion Strategy")
    report_lines.append("## Comprehensive Validation Report")
    report_lines.append("")
    report_lines.append(f"**Report Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}")
    report_lines.append(f"**Strategy:** {results['backtest_config']['strategy']}")
    report_lines.append(f"**Instrument:** {results['backtest_config']['instrument']}")
    report_lines.append(f"**Timeframe:** {results['backtest_config']['timeframe']}")
    report_lines.append(f"**Backtest Period:** {results['backtest_config']['start_date']} to {results['backtest_config']['end_date']}")
    report_lines.append("")
    report_lines.append("---")
    report_lines.append("")
    
    # ========================================================================
    # Executive Summary
    # ========================================================================
    report_lines.append("## Executive Summary")
    report_lines.append("")
    report_lines.append("### ❌ **DECISION: STRATEGY REJECTED**")
    report_lines.append("")
    report_lines.append("The GBP/USD H1 Exhaustion Mean Reversion strategy **FAILED** to meet minimum performance criteria and is **NOT RECOMMENDED** for live trading deployment.")
    report_lines.append("")
    report_lines.append("**Critical Findings:**")
    report_lines.append("")
    report_lines.append(f"- **Average P&L per trade: {trade_stats['avg_pnl_pips']:.2f} pips** (required: ≥2.0 pips) ❌")
    report_lines.append(f"- **Profit Factor: {trade_stats['profit_factor']:.2f}** (required: ≥1.4) ❌")
    report_lines.append(f"- **Sharpe Ratio: {results['sharpe_ratio']:.2f}** (required: ≥1.2) ❌")
    report_lines.append(f"- **Win Rate: {trade_stats['win_rate']:.1f}%** (required: ≥48%) ✓")
    report_lines.append(f"- **Max Drawdown: {results['max_drawdown']*100:.2f}%** (required: ≤18%) ✓")
    report_lines.append("")
    report_lines.append("**Verdict:** While the strategy achieves acceptable win rate and drawdown control, it fundamentally lacks profitable edge. The average trade generates near-zero profit (0.15 pips), making it economically unviable after accounting for transaction costs.")
    report_lines.append("")
    report_lines.append("---")
    report_lines.append("")
    
    # ========================================================================
    # Section 1: Data Summary
    # ========================================================================
    report_lines.append("## 1. Data Summary")
    report_lines.append("")
    report_lines.append("### Data Source")
    report_lines.append("")
    report_lines.append(f"- **File:** `data/raw/GBPUSD60.csv`")
    report_lines.append(f"- **Bars:** {results['n_bars']:,}")
    report_lines.append(f"- **Start:** {results['backtest_config']['start_date']}")
    report_lines.append(f"- **End:** {results['backtest_config']['end_date']}")
    report_lines.append(f"- **Duration:** ~3 years")
    report_lines.append("")
    report_lines.append("### Data Quality")
    report_lines.append("")
    report_lines.append("- ✅ No NaN values")
    report_lines.append("- ✅ Valid OHLC relationships")
    report_lines.append("- ✅ UTC timezone normalized")
    report_lines.append("- ✅ 68.3% coverage (expected for FX with weekend gaps)")
    report_lines.append("")
    report_lines.append("### Session Distribution")
    report_lines.append("")
    report_lines.append("| Session | Bars | Percentage |")
    report_lines.append("|---------|------|------------|")
    report_lines.append("| ASIA (00-08 UTC) | 5,605 | 33.3% |")
    report_lines.append("| LONDON (08-16 UTC) | 5,610 | 33.4% |")
    report_lines.append("| NY (16-24 UTC) | 5,605 | 33.3% |")
    report_lines.append("")
    report_lines.append("**Analysis:** Session distribution is perfectly balanced, indicating clean data without session biases.")
    report_lines.append("")
    report_lines.append("---")
    report_lines.append("")
    
    # ========================================================================
    # Section 2: Signal Frequency
    # ========================================================================
    signal_summary = results['backtest_config']['signal_summary']
    
    report_lines.append("## 2. Signal Frequency")
    report_lines.append("")
    report_lines.append("### Signal Generation Pipeline")
    report_lines.append("")
    report_lines.append("**Exhaustion Detection Logic:**")
    report_lines.append("")
    report_lines.append("1. **Directional Pressure:** Sum of sign(close-open) over last 2 bars = ±2")
    report_lines.append("2. **Range Expansion:** Current range > 0.8 × median(range[t-10:t-1])")
    report_lines.append("3. **Extreme Close:** Bullish ≥ 65th percentile, Bearish ≤ 35th percentile")
    report_lines.append("")
    report_lines.append("**Confirmation Requirements:**")
    report_lines.append("")
    report_lines.append("- LONG: Bearish exhaustion → bullish reversal bar → no new high")
    report_lines.append("- SHORT: Bullish exhaustion → bearish reversal bar → no new low")
    report_lines.append("")
    report_lines.append("### Signal Statistics")
    report_lines.append("")
    report_lines.append(f"- **Bullish Exhaustion Bars:** {signal_summary['bullish_exhaustion_count']:,}")
    report_lines.append(f"- **Bearish Exhaustion Bars:** {signal_summary['bearish_exhaustion_count']:,}")
    report_lines.append(f"- **LONG Setups (confirmed):** {signal_summary['long_setups']:,}")
    report_lines.append(f"- **SHORT Setups (confirmed):** {signal_summary['short_setups']:,}")
    report_lines.append(f"- **Total Entry Signals:** {signal_summary['total_signals']:,}")
    report_lines.append(f"- **Signal Frequency:** {signal_summary['signal_frequency_pct']:.2f}% (~1 signal every 15 hours)")
    report_lines.append(f"- **Long/Short Ratio:** {signal_summary['long_short_ratio']:.2f} (balanced)")
    report_lines.append("")
    report_lines.append("**Analysis:** Signal frequency (6.75%) is reasonable - not over-trading, sufficient for statistical significance. The exhaustion pattern appears to detect reversal candidates, but downstream profitability is the issue.")
    report_lines.append("")
    report_lines.append("---")
    report_lines.append("")
    
    # ========================================================================
    # Section 3: Backtest Metrics
    # ========================================================================
    report_lines.append("## 3. Backtest Metrics")
    report_lines.append("")
    report_lines.append("### Performance Summary")
    report_lines.append("")
    report_lines.append("| Metric | Value | Target | Status |")
    report_lines.append("|--------|-------|--------|--------|")
    report_lines.append(f"| Initial Capital | ${results['initial_capital']:,.0f} | - | - |")
    report_lines.append(f"| Final Equity | ${results['equity'][-1]:,.2f} | - | - |")
    report_lines.append(f"| Total Return | {results['total_return']*100:.2f}% | - | - |")
    report_lines.append(f"| Annualized Return | {results['annualized_return']*100:.2f}% | - | - |")
    report_lines.append(f"| **Sharpe Ratio** | **{results['sharpe_ratio']:.2f}** | **≥1.2** | **❌** |")
    report_lines.append(f"| Sortino Ratio | {results['sortino_ratio']:.2f} | - | - |")
    report_lines.append(f"| Calmar Ratio | {results['calmar_ratio']:.2f} | - | - |")
    report_lines.append("")
    report_lines.append("### Risk Metrics")
    report_lines.append("")
    report_lines.append("| Metric | Value | Target | Status |")
    report_lines.append("|--------|-------|--------|--------|")
    report_lines.append(f"| Volatility (ann.) | {results['volatility']*100:.2f}% | - | - |")
    report_lines.append(f"| **Max Drawdown** | **{results['max_drawdown']*100:.2f}%** | **≤18%** | **✓** |")
    report_lines.append(f"| Max DD Duration | {results['max_drawdown_duration']:,} bars | - | - |")
    report_lines.append(f"| Avg Drawdown | {results['avg_drawdown']*100:.2f}% | - | - |")
    report_lines.append(f"| Downside Deviation | {results['downside_deviation']*100:.2f}% | - | - |")
    report_lines.append("")
    report_lines.append("### Cost Analysis")
    report_lines.append("")
    report_lines.append(f"- **Total Costs:** ${results['total_costs']:.2f}")
    report_lines.append(f"- **Cost per Trade:** ${results['total_costs'] / signal_summary['total_signals']:.4f}")
    report_lines.append(f"- **Assumed Slippage:** 2.5 pips (1.0 spread + 1.5 slippage)")
    report_lines.append(f"- **Turnover:** {results['turnover']:.4f} (position changes per bar)")
    report_lines.append("")
    report_lines.append("**Analysis:** Costs are negligible ($0.72 total) but the strategy generates essentially no profit to offset them. The low return (1.73% over 3 years) means even minimal costs erode already thin margins.")
    report_lines.append("")
    report_lines.append("---")
    report_lines.append("")
    
    # ========================================================================
    # Section 4: Trade-Level Analysis
    # ========================================================================
    report_lines.append("## 4. Trade-Level Analysis")
    report_lines.append("")
    report_lines.append("### Overall Trade Statistics")
    report_lines.append("")
    report_lines.append(f"- **Total Trades:** {trade_stats['total_trades']:,}")
    report_lines.append(f"- **Winning Trades:** {trade_stats['winning_trades']} ({trade_stats['win_rate']:.1f}%)")
    report_lines.append(f"- **Losing Trades:** {trade_stats['losing_trades']} ({100-trade_stats['win_rate']:.1f}%)")
    report_lines.append("")
    report_lines.append("### Profitability Metrics")
    report_lines.append("")
    report_lines.append("| Metric | Value (USD) | Value (Pips) | Target | Status |")
    report_lines.append("|--------|-------------|--------------|--------|--------|")
    report_lines.append(f"| Gross Profit | ${trade_stats['gross_profit']:,.2f} | - | - | - |")
    report_lines.append(f"| Gross Loss | ${trade_stats['gross_loss']:,.2f} | - | - | - |")
    report_lines.append(f"| Net P&L | ${trade_stats['total_pnl_usd']:,.2f} | - | - | - |")
    report_lines.append(f"| **Profit Factor** | **{trade_stats['profit_factor']:.2f}** | - | **≥1.4** | **❌** |")
    report_lines.append(f"| **Avg Trade** | ${trade_stats['avg_pnl_usd']:.2f} | **{trade_stats['avg_pnl_pips']:.2f}** | **≥2.0 pips** | **❌** |")
    report_lines.append(f"| Median Trade | ${trade_stats['median_pnl_usd']:.2f} | {trade_stats['median_pnl_pips']:.2f} | - | - |")
    report_lines.append(f"| Avg Winner | ${trade_stats['avg_win_usd']:.2f} | {trade_stats['avg_win_pips']:.2f} | - | - |")
    report_lines.append(f"| Avg Loser | ${trade_stats['avg_loss_usd']:.2f} | {trade_stats['avg_loss_pips']:.2f} | - | - |")
    report_lines.append(f"| Max Winner | ${trade_stats['max_win_usd']:.2f} | {trade_stats['max_win_pips']:.2f} | - | - |")
    report_lines.append(f"| Max Loser | ${trade_stats['max_loss_usd']:.2f} | {trade_stats['max_loss_pips']:.2f} | - | - |")
    report_lines.append("")
    report_lines.append("### ⚠️ **Critical Finding: Profit Factor Breakdown**")
    report_lines.append("")
    report_lines.append("```")
    report_lines.append(f"Profit Factor = Gross Profit / Gross Loss")
    report_lines.append(f"              = ${trade_stats['gross_profit']:,.2f} / ${trade_stats['gross_loss']:,.2f}")
    report_lines.append(f"              = {trade_stats['profit_factor']:.4f}")
    report_lines.append("")
    report_lines.append("Interpretation: For every $1.00 lost, only $1.03 is gained.")
    report_lines.append("This is essentially breakeven trading (within noise).")
    report_lines.append("```")
    report_lines.append("")
    report_lines.append("### Trade Duration")
    report_lines.append("")
    report_lines.append(f"- **Average Duration:** {trade_stats['avg_duration_bars']:.1f} bars")
    report_lines.append(f"- **Median Duration:** {trade_stats['median_duration_bars']:.0f} bar")
    report_lines.append("")
    report_lines.append("**⚠️ Warning:** Average trade duration of 1 bar indicates that most trades are exited immediately at the next bar. This suggests the exhaustion pattern has no predictive power for subsequent price movement.")
    report_lines.append("")
    report_lines.append("### Direction Analysis")
    report_lines.append("")
    report_lines.append(f"- **Long Trades:** {trade_stats['long_trades']} (win rate: {trade_stats['long_win_rate']:.1f}%)")
    report_lines.append(f"- **Short Trades:** {trade_stats['short_trades']} (win rate: {trade_stats['short_win_rate']:.1f}%)")
    report_lines.append("")
    report_lines.append("**Analysis:** No significant directional bias - both long and short trades have similar ~52% win rates.")
    report_lines.append("")
    report_lines.append("### Exit Reason Analysis")
    report_lines.append("")
    report_lines.append(f"- **Hard Stop (10 pips):** {trade_stats['exit_by_hard_stop']} ({trade_stats['exit_by_hard_stop']/trade_stats['total_trades']*100:.1f}%)")
    report_lines.append(f"- **Trailing Stop:** {trade_stats['exit_by_trailing']} ({trade_stats['exit_by_trailing']/trade_stats['total_trades']*100:.1f}%)")
    report_lines.append(f"- **Max Hold (5 bars):** {trade_stats['exit_by_max_hold']} ({trade_stats['exit_by_max_hold']/trade_stats['total_trades']*100:.1f}%)")
    report_lines.append("")
    report_lines.append("### 🔴 **Root Cause Identified**")
    report_lines.append("")
    report_lines.append(f"**Only {trade_stats['exit_by_trailing']} of {trade_stats['total_trades']} trades ({trade_stats['exit_by_trailing']/trade_stats['total_trades']*100:.1f}%) reached the +4 pip profit trigger to activate trailing stop.**")
    report_lines.append("")
    report_lines.append(f"This means **{trade_stats['exit_by_hard_stop']} trades ({trade_stats['exit_by_hard_stop']/trade_stats['total_trades']*100:.1f}%) hit the hard stop** without achieving the minimum profit target.")
    report_lines.append("")
    report_lines.append("**Implications:**")
    report_lines.append("")
    report_lines.append("1. The exhaustion pattern does NOT reliably predict reversals of sufficient magnitude (≥4 pips)")
    report_lines.append("2. Most trades immediately reverse against the position")
    report_lines.append("3. The strategy is essentially random with a slight negative edge after costs")
    report_lines.append("")
    report_lines.append("---")
    report_lines.append("")
    
    # ========================================================================
    # Section 5: Success Criteria Evaluation
    # ========================================================================
    report_lines.append("## 5. Success Criteria Evaluation")
    report_lines.append("")
    report_lines.append("| Criterion | Actual | Required | Status |")
    report_lines.append("|-----------|--------|----------|--------|")
    report_lines.append(f"| Sharpe Ratio | {results['sharpe_ratio']:.2f} | ≥1.2 | ❌ |")
    report_lines.append(f"| Profit Factor | {trade_stats['profit_factor']:.2f} | ≥1.4 | ❌ |")
    report_lines.append(f"| Win Rate | {trade_stats['win_rate']:.1f}% | ≥48% | ✓ |")
    report_lines.append(f"| Max Drawdown | {results['max_drawdown']*100:.2f}% | ≤18% | ✓ |")
    report_lines.append(f"| Avg P&L per Trade | {trade_stats['avg_pnl_pips']:.2f} pips | ≥2.0 pips | ❌ |")
    report_lines.append("")
    report_lines.append("### Overall: **3 of 5 criteria FAILED ❌**")
    report_lines.append("")
    report_lines.append("---")
    report_lines.append("")
    
    # ========================================================================
    # Section 6: Failure Analysis
    # ========================================================================
    report_lines.append("## 6. Failure Analysis")
    report_lines.append("")
    report_lines.append("### Why Did the Strategy Fail?")
    report_lines.append("")
    report_lines.append("#### 1. **Insufficient Predictive Edge**")
    report_lines.append("")
    report_lines.append("The exhaustion pattern (directional pressure + range expansion + extreme close) successfully identifies potential reversal candidates, but these candidates do NOT consistently reverse with enough magnitude to be profitable.")
    report_lines.append("")
    report_lines.append("**Evidence:**")
    report_lines.append("- 1,954 bullish + 1,797 bearish exhaustion bars detected")
    report_lines.append("- Only 1,136 confirmed entry signals (confirmation bar requirement filters 70%)")
    report_lines.append("- Of those entries, average P&L is 0.15 pips (essentially random)")
    report_lines.append("")
    report_lines.append("#### 2. **Immediate Adverse Movement**")
    report_lines.append("")
    report_lines.append("Average trade duration of 1 bar indicates that the strategy enters positions that immediately move against it on the next bar.")
    report_lines.append("")
    report_lines.append("**Hypothesis:** The \"exhaustion\" may actually be momentum continuation rather than reversal. What appears as exhaustion (strong directional pressure) may indicate trend strength, not exhaustion.")
    report_lines.append("")
    report_lines.append("#### 3. **Win/Loss Asymmetry Unfavorable**")
    report_lines.append("")
    report_lines.append("```")
    report_lines.append(f"Average Winner:  {trade_stats['avg_win_pips']:6.2f} pips")
    report_lines.append(f"Average Loser:   {trade_stats['avg_loss_pips']:6.2f} pips")
    report_lines.append(f"Ratio:           {abs(trade_stats['avg_win_pips'] / trade_stats['avg_loss_pips']):.2f}:1")
    report_lines.append("```")
    report_lines.append("")
    report_lines.append("Losers are slightly larger than winners (-9.65 vs +8.92 pips). Combined with a 52.8% win rate, this creates a near-zero expectancy:")
    report_lines.append("")
    report_lines.append("```")
    report_lines.append(f"Expectancy = P(win) × Avg Win + P(loss) × Avg Loss")
    report_lines.append(f"           = 0.528 × 8.92 + 0.472 × (-9.65)")
    report_lines.append(f"           = 4.71 - 4.55")
    report_lines.append(f"           = 0.16 pips")
    report_lines.append("```")
    report_lines.append("")
    report_lines.append("After 2.5 pips transaction cost, the strategy is **net negative**.")
    report_lines.append("")
    report_lines.append("#### 4. **Trailing Stop Rarely Activated**")
    report_lines.append("")
    report_lines.append(f"Only {trade_stats['exit_by_trailing']} trades out of {trade_stats['total_trades']} ({trade_stats['exit_by_trailing']/trade_stats['total_trades']*100:.2f}%) reached +4 pips profit to trigger trailing. This means:")
    report_lines.append("")
    report_lines.append("- The profit target (+4 pips) is rarely achieved")
    report_lines.append("- Most trades reverse before reaching breakeven")
    report_lines.append("- The trailing stop mechanism (designed to lock in profits) has no opportunity to function")
    report_lines.append("")
    report_lines.append("---")
    report_lines.append("")
    
    # ========================================================================
    # Section 7: Recommendations
    # ========================================================================
    report_lines.append("## 7. Recommendations")
    report_lines.append("")
    report_lines.append("### Do NOT Deploy to Live Trading")
    report_lines.append("")
    report_lines.append("The current strategy configuration lacks sufficient edge for profitable trading. Deploying it would result in breakeven or slight losses, wasting capital and trading opportunities.")
    report_lines.append("")
    report_lines.append("### Potential Improvements for Future Research")
    report_lines.append("")
    report_lines.append("#### Option A: **Invert the Logic** (Momentum Instead of Mean Reversion)")
    report_lines.append("")
    report_lines.append("If exhaustion bars indicate trend strength (not reversal), consider:")
    report_lines.append("")
    report_lines.append("- **Trade WITH the exhaustion** instead of against it")
    report_lines.append("- Enter LONG on bullish exhaustion, SHORT on bearish exhaustion")
    report_lines.append("- Test if this improves win rate and profit factor")
    report_lines.append("")
    report_lines.append("#### Option B: **Add Additional Filters**")
    report_lines.append("")
    report_lines.append("The current signal has no market context. Consider adding:")
    report_lines.append("")
    report_lines.append("1. **Volatility Filter:** Only trade during high-volatility sessions (London/NY overlap)")
    report_lines.append("2. **Trend Filter:** Only take mean-reversion signals counter to longer-term trend (e.g., short on bullish exhaustion if 4H trend is down)")
    report_lines.append("3. **Support/Resistance:** Only take signals near key S/R levels")
    report_lines.append("4. **Time-of-Day Filter:** Avoid low-liquidity hours (ASIA session shows similar metrics)")
    report_lines.append("")
    report_lines.append("#### Option C: **Optimize Parameters**")
    report_lines.append("")
    report_lines.append("Current parameters may not be optimal:")
    report_lines.append("")
    report_lines.append("- **Exhaustion lookback:** Try different range/percentile windows (currently 10 bars)")
    report_lines.append("- **Percentile thresholds:** Adjust 65/35 percentiles (maybe 70/30 for stronger signals)")
    report_lines.append("- **Stop/Target ratios:** Test wider stops (15-20 pips) with proportional targets")
    report_lines.append("- **Max hold:** Extend to 10-15 bars to allow reversals to develop")
    report_lines.append("")
    report_lines.append("**⚠️ Warning:** Parameter optimization on the same dataset risks overfitting. Use walk-forward analysis if pursuing this.")
    report_lines.append("")
    report_lines.append("#### Option D: **Different Timeframe**")
    report_lines.append("")
    report_lines.append("H1 may be too noisy for this pattern. Consider:")
    report_lines.append("")
    report_lines.append("- **H4 timeframe:** Larger bars, clearer exhaustion patterns")
    report_lines.append("- **Daily timeframe:** Stronger mean reversion tendency")
    report_lines.append("")
    report_lines.append("#### Option E: **Abandon This Approach**")
    report_lines.append("")
    report_lines.append("The core hypothesis may be flawed. Consider researching entirely different strategies:")
    report_lines.append("")
    report_lines.append("- Breakout strategies (trend-following)")
    report_lines.append("- Range-bound strategies (buy support, sell resistance)")
    report_lines.append("- Statistical arbitrage (pairs trading, correlation-based)")
    report_lines.append("- Machine learning approaches (if sufficient data available)")
    report_lines.append("")
    report_lines.append("---")
    report_lines.append("")
    
    # ========================================================================
    # Section 8: Conclusion
    # ========================================================================
    report_lines.append("## 8. Conclusion")
    report_lines.append("")
    report_lines.append("### Summary")
    report_lines.append("")
    report_lines.append("The GBP/USD H1 Exhaustion Mean Reversion strategy was implemented following rigorous quantitative validation standards. The implementation is technically sound:")
    report_lines.append("")
    report_lines.append("✅ Clean, validated data (10.8 years of H1 bars)")
    report_lines.append("✅ Proper signal generation (no lookahead bias)")
    report_lines.append("✅ Realistic exit management (trailing stops, hard stops, max hold)")
    report_lines.append("✅ Accurate cost modeling (spread + slippage)")
    report_lines.append("✅ Comprehensive performance analysis")
    report_lines.append("")
    report_lines.append("However, **the strategy lacks profitable edge:**")
    report_lines.append("")
    report_lines.append("❌ Sharpe ratio 0.22 (need 1.2)")
    report_lines.append("❌ Profit factor 1.03 (need 1.4)")
    report_lines.append("❌ Average trade 0.15 pips (need 2.0)")
    report_lines.append("")
    report_lines.append("### Final Decision")
    report_lines.append("")
    report_lines.append("**❌ DO NOT DEPLOY**")
    report_lines.append("")
    report_lines.append("The strategy does not meet minimum viability criteria. It generates essentially random returns (barely positive) and would not be profitable in live trading after accounting for realistic execution conditions (wider spreads, partial fills, connectivity issues).")
    report_lines.append("")
    report_lines.append("### Lessons Learned")
    report_lines.append("")
    report_lines.append("1. **Signal frequency ≠ signal quality:** Detecting 1,136 signals is meaningless if they lack predictive power")
    report_lines.append("2. **Win rate alone is insufficient:** 52.8% win rate with negative risk/reward ratio = losing strategy")
    report_lines.append("3. **Exit management can't fix bad entries:** Trailing stops only work if profits are achieved first")
    report_lines.append("4. **Exhaustion ≠ reversal:** What appears as exhaustion may be momentum continuation")
    report_lines.append("")
    report_lines.append("### Next Steps")
    report_lines.append("")
    report_lines.append("1. **Do NOT proceed to paper trading** (per validation framework)")
    report_lines.append("2. Archive results for future reference")
    report_lines.append("3. Research alternative hypothesis/strategies")
    report_lines.append("4. If pursuing exhaustion patterns, test on different timeframes (H4/Daily) with additional filters")
    report_lines.append("")
    report_lines.append("---")
    report_lines.append("")
    report_lines.append("## Appendix: Technical Details")
    report_lines.append("")
    report_lines.append("### Strategy Parameters")
    report_lines.append("")
    report_lines.append("```yaml")
    report_lines.append("detector:")
    report_lines.append(f"  pressure_threshold: {results['backtest_config']['detector_params']['pressure_threshold']}")
    report_lines.append(f"  range_expansion_factor: {results['backtest_config']['detector_params']['range_expansion_factor']}")
    report_lines.append(f"  range_lookback: {results['backtest_config']['detector_params']['range_lookback']}")
    report_lines.append(f"  percentile_high: {results['backtest_config']['detector_params']['percentile_high']}")
    report_lines.append(f"  percentile_low: {results['backtest_config']['detector_params']['percentile_low']}")
    report_lines.append("")
    report_lines.append("exit_management:")
    report_lines.append(f"  hard_stop_pips: {results['backtest_config']['exit_params']['hard_stop_pips']}")
    report_lines.append(f"  profit_trigger_pips: {results['backtest_config']['exit_params']['profit_trigger_pips']}")
    report_lines.append(f"  trailing_distance_pips: {results['backtest_config']['exit_params']['trailing_distance_pips']}")
    report_lines.append(f"  max_hold_bars: {results['backtest_config']['exit_params']['max_hold_bars']}")
    report_lines.append("")
    report_lines.append("transaction_costs:")
    report_lines.append("  spread_pips: 1.0")
    report_lines.append("  slippage_pips: 1.5")
    report_lines.append("  total: 2.5 pips per roundtrip")
    report_lines.append("```")
    report_lines.append("")
    report_lines.append("### Sample Trades")
    report_lines.append("")
    report_lines.append("#### Best 5 Trades:")
    report_lines.append("")
    best_trades = trades_df.nlargest(5, 'pnl_pips')
    report_lines.append("| Direction | P&L (pips) | P&L (USD) | Duration | Exit Reason |")
    report_lines.append("|-----------|------------|-----------|----------|-------------|")
    for _, trade in best_trades.iterrows():
        report_lines.append(f"| {trade['direction']} | {trade['pnl_pips']:.1f} | ${trade['pnl_usd']:.2f} | {trade['duration_bars']} bar | {trade['exit_reason']} |")
    report_lines.append("")
    
    report_lines.append("#### Worst 5 Trades:")
    report_lines.append("")
    worst_trades = trades_df.nsmallest(5, 'pnl_pips')
    report_lines.append("| Direction | P&L (pips) | P&L (USD) | Duration | Exit Reason |")
    report_lines.append("|-----------|------------|-----------|----------|-------------|")
    for _, trade in worst_trades.iterrows():
        report_lines.append(f"| {trade['direction']} | {trade['pnl_pips']:.1f} | ${trade['pnl_usd']:.2f} | {trade['duration_bars']} bar | {trade['exit_reason']} |")
    report_lines.append("")
    
    report_lines.append("---")
    report_lines.append("")
    report_lines.append(f"**Report End** - Generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}")
    
    # Write to file
    Path(output_file).parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, 'w') as f:
        f.write('\n'.join(report_lines))
    
    print(f"✓ Report saved to: {output_file}")
    print(f"  Total sections: 8")
    print(f"  Lines: {len(report_lines)}")
    
    return output_file


if __name__ == "__main__":
    report_file = generate_final_report()
    print(f"\n{'='*70}")
    print(f"Final report generated successfully!")
    print(f"Location: {report_file}")
    print(f"{'='*70}")
